[package]
resolver = "3"
name = "abc-parser"
version = "0.1.0"
description = "A recovering, source-spanned parser for ABC music notation 2.1"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.95"

[dependencies]
chumsky = "0.11.1"
clap = { version = "4.5.54", default-features = false, features = ["derive", "error-context", "help", "std", "usage"] }
merman-rustdoc = "0.7.0"

[[bin]]
name = "abc-transpose"
path = "src/bin/abc-transpose.rs"
doc = true

[lints.rust]
missing_docs = "deny"
unsafe_code = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
