[workspace]
members = ["abc-language-server", "abc-parser"]
resolver = "3"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
clone_on_ref_ptr = "deny"
missing_errors_doc = "allow"
must_use_candidate = "allow"
option_if_let_else = "allow"
